"""Ledger Event Type Taxonomy — static, deterministic event type constants."""

from __future__ import annotations

# Source events
SOURCE_INGESTED = "SOURCE_INGESTED"
SOURCE_SPAN_CREATED = "SOURCE_SPAN_CREATED"

# Claim events
CLAIM_PROPOSED = "CLAIM_PROPOSED"
CLAIM_REJECTED_SCHEMA = "CLAIM_REJECTED_SCHEMA"
CLAIM_GROUNDED = "CLAIM_GROUNDED"
CLAIM_GROUNDING_BLOCKED = "CLAIM_GROUNDING_BLOCKED"
CLAIM_SOURCE_SUPPORTED = "CLAIM_SOURCE_SUPPORTED"
CLAIM_SOURCE_SUPPORT_BLOCKED = "CLAIM_SOURCE_SUPPORT_BLOCKED"

# Proposal events
PROPOSAL_VALIDATED = "PROPOSAL_VALIDATED"
PROPOSAL_REJECTED = "PROPOSAL_REJECTED"
PROPOSAL_ACCEPTED_AS_CANDIDATE = "PROPOSAL_ACCEPTED_AS_CANDIDATE"

# Ontology events
ONTOLOGY_RELATION_PROPOSED = "ONTOLOGY_RELATION_PROPOSED"
ONTOLOGY_RELATION_VALIDATED = "ONTOLOGY_RELATION_VALIDATED"
ONTOLOGY_RELATION_ACTIVATED = "ONTOLOGY_RELATION_ACTIVATED"
ONTOLOGY_RELATION_REJECTED = "ONTOLOGY_RELATION_REJECTED"
ONTOLOGY_RELATION_DEPRECATED = "ONTOLOGY_RELATION_DEPRECATED"
ONTOLOGY_RELATION_SUPERSEDED = "ONTOLOGY_RELATION_SUPERSEDED"
ONTOLOGY_RELATION_ROLLED_BACK = "ONTOLOGY_RELATION_ROLLED_BACK"

# Proof events
PROOF_EVALUATED = "PROOF_EVALUATED"
PROOF_VALIDATION_FAILED = "PROOF_VALIDATION_FAILED"

# Trust/promotion events
PROMOTION_BLOCKED_ZERO_PROOFS = "PROMOTION_BLOCKED_ZERO_PROOFS"
PROMOTION_BLOCKED_NON_VERIFIED_STATUS = "PROMOTION_BLOCKED_NON_VERIFIED_STATUS"
PROMOTION_GRANTED_T4 = "PROMOTION_GRANTED_T4"

# Certification events
CERTIFICATION_BLOCKED = "CERTIFICATION_BLOCKED"
CERTIFICATION_GRANTED_T5 = "CERTIFICATION_GRANTED_T5"

# Conflict events
CONFLICT_DETECTED = "CONFLICT_DETECTED"
CONFLICT_RESOLVED = "CONFLICT_RESOLVED"

# Policy events
POLICY_ACTION_APPLIED = "POLICY_ACTION_APPLIED"
POLICY_ACTION_BLOCKED = "POLICY_ACTION_BLOCKED"

# Runtime events
RUNTIME_VALIDATED = "RUNTIME_VALIDATED"
RUNTIME_VALIDATION_FAILED = "RUNTIME_VALIDATION_FAILED"

# Distribution/bundle events
BUNDLE_VERIFIED = "BUNDLE_VERIFIED"
BUNDLE_VERIFICATION_FAILED = "BUNDLE_VERIFICATION_FAILED"

# API events
API_REQUEST_VALIDATED = "API_REQUEST_VALIDATED"
API_REQUEST_REJECTED = "API_REQUEST_REJECTED"

# Event categories
CATEGORY_SOURCE = "SOURCE"
CATEGORY_CLAIM = "CLAIM"
CATEGORY_PROPOSAL = "PROPOSAL"
CATEGORY_ONTOLOGY = "ONTOLOGY"
CATEGORY_PROOF = "PROOF"
CATEGORY_TRUST = "TRUST"
CATEGORY_CERTIFICATION = "CERTIFICATION"
CATEGORY_CONFLICT = "CONFLICT"
CATEGORY_POLICY = "POLICY"
CATEGORY_RUNTIME = "RUNTIME"
CATEGORY_DISTRIBUTION = "DISTRIBUTION"
CATEGORY_API = "API"

KNOWN_CATEGORIES: frozenset[str] = frozenset({
    CATEGORY_SOURCE,
    CATEGORY_CLAIM,
    CATEGORY_PROPOSAL,
    CATEGORY_ONTOLOGY,
    CATEGORY_PROOF,
    CATEGORY_TRUST,
    CATEGORY_CERTIFICATION,
    CATEGORY_CONFLICT,
    CATEGORY_POLICY,
    CATEGORY_RUNTIME,
    CATEGORY_DISTRIBUTION,
    CATEGORY_API,
})

_EVENT_CATEGORY_MAP: dict[str, str] = {
    SOURCE_INGESTED: CATEGORY_SOURCE,
    SOURCE_SPAN_CREATED: CATEGORY_SOURCE,
    CLAIM_PROPOSED: CATEGORY_CLAIM,
    CLAIM_REJECTED_SCHEMA: CATEGORY_CLAIM,
    CLAIM_GROUNDED: CATEGORY_CLAIM,
    CLAIM_GROUNDING_BLOCKED: CATEGORY_CLAIM,
    CLAIM_SOURCE_SUPPORTED: CATEGORY_CLAIM,
    CLAIM_SOURCE_SUPPORT_BLOCKED: CATEGORY_CLAIM,
    PROPOSAL_VALIDATED: CATEGORY_PROPOSAL,
    PROPOSAL_REJECTED: CATEGORY_PROPOSAL,
    PROPOSAL_ACCEPTED_AS_CANDIDATE: CATEGORY_PROPOSAL,
    ONTOLOGY_RELATION_PROPOSED: CATEGORY_ONTOLOGY,
    ONTOLOGY_RELATION_VALIDATED: CATEGORY_ONTOLOGY,
    ONTOLOGY_RELATION_ACTIVATED: CATEGORY_ONTOLOGY,
    ONTOLOGY_RELATION_REJECTED: CATEGORY_ONTOLOGY,
    ONTOLOGY_RELATION_DEPRECATED: CATEGORY_ONTOLOGY,
    ONTOLOGY_RELATION_SUPERSEDED: CATEGORY_ONTOLOGY,
    ONTOLOGY_RELATION_ROLLED_BACK: CATEGORY_ONTOLOGY,
    PROOF_EVALUATED: CATEGORY_PROOF,
    PROOF_VALIDATION_FAILED: CATEGORY_PROOF,
    PROMOTION_BLOCKED_ZERO_PROOFS: CATEGORY_TRUST,
    PROMOTION_BLOCKED_NON_VERIFIED_STATUS: CATEGORY_TRUST,
    PROMOTION_GRANTED_T4: CATEGORY_TRUST,
    CERTIFICATION_BLOCKED: CATEGORY_CERTIFICATION,
    CERTIFICATION_GRANTED_T5: CATEGORY_CERTIFICATION,
    CONFLICT_DETECTED: CATEGORY_CONFLICT,
    CONFLICT_RESOLVED: CATEGORY_CONFLICT,
    POLICY_ACTION_APPLIED: CATEGORY_POLICY,
    POLICY_ACTION_BLOCKED: CATEGORY_POLICY,
    RUNTIME_VALIDATED: CATEGORY_RUNTIME,
    RUNTIME_VALIDATION_FAILED: CATEGORY_RUNTIME,
    BUNDLE_VERIFIED: CATEGORY_DISTRIBUTION,
    BUNDLE_VERIFICATION_FAILED: CATEGORY_DISTRIBUTION,
    API_REQUEST_VALIDATED: CATEGORY_API,
    API_REQUEST_REJECTED: CATEGORY_API,
}

KNOWN_EVENT_TYPES: frozenset[str] = frozenset(_EVENT_CATEGORY_MAP.keys())


def is_known_event_type(event_type: str) -> bool:
    return event_type in KNOWN_EVENT_TYPES


def event_category(event_type: str) -> str:
    """Return category for a known event type, or raise KeyError."""
    return _EVENT_CATEGORY_MAP[event_type]
