"""Renderer Guard + Answer Verification (v6.16.0)."""

from vcse.render.model import (
    AnswerClaimRef,
    AnswerDraft,
    RendererGuardDecision,
    RendererGuardPolicy,
    ValidatedClaimView,
    RENDER_VALID,
    RENDER_INVALID,
    RENDER_NEEDS_CLAIM_MAP,
    RENDER_EXCEEDS_VALIDATED_MATERIAL,
    RENDER_POLICY_BLOCKED,
    RENDER_GUARD_PASSED,
    MISSING_ANSWER_ID,
    MISSING_RENDERED_TEXT,
    MISSING_CLAIM_REFS,
    UNKNOWN_CLAIM_ID,
    CLAIM_STATUS_NOT_ALLOWED,
    RENDERED_TEXT_NOT_CANONICAL,
    UNSUPPORTED_SEGMENT_PRESENT,
    SOURCE_SPAN_MISMATCH,
    INVALID_RENDER_MODE,
    INVALID_RENDER_INPUT,
    NON_FINITE_VALUE,
    UNKNOWN_FIELD,
    CANONICAL_ONLY,
    NORMALIZED_CANONICAL,
    EXPLICIT_ALLOWED_RENDERING,
    DEFAULT_ALLOWED_CLAIM_STATUSES,
)
from vcse.render.service import verify_rendered_answer
from vcse.render.serialize import renderer_guard_decision_to_dict, renderer_guard_decision_to_json

__all__ = [
    "AnswerClaimRef",
    "AnswerDraft",
    "RendererGuardDecision",
    "RendererGuardPolicy",
    "ValidatedClaimView",
    "RENDER_VALID",
    "RENDER_INVALID",
    "RENDER_NEEDS_CLAIM_MAP",
    "RENDER_EXCEEDS_VALIDATED_MATERIAL",
    "RENDER_POLICY_BLOCKED",
    "RENDER_GUARD_PASSED",
    "MISSING_ANSWER_ID",
    "MISSING_RENDERED_TEXT",
    "MISSING_CLAIM_REFS",
    "UNKNOWN_CLAIM_ID",
    "CLAIM_STATUS_NOT_ALLOWED",
    "RENDERED_TEXT_NOT_CANONICAL",
    "UNSUPPORTED_SEGMENT_PRESENT",
    "SOURCE_SPAN_MISMATCH",
    "INVALID_RENDER_MODE",
    "INVALID_RENDER_INPUT",
    "NON_FINITE_VALUE",
    "UNKNOWN_FIELD",
    "CANONICAL_ONLY",
    "NORMALIZED_CANONICAL",
    "EXPLICIT_ALLOWED_RENDERING",
    "DEFAULT_ALLOWED_CLAIM_STATUSES",
    "verify_rendered_answer",
    "renderer_guard_decision_to_dict",
    "renderer_guard_decision_to_json",
]
